name: Build & Deploy to ECS (Fargate)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: Optional image tag to deploy (defaults to branch-SHA)
        required: false

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: trupick-next
  ECS_CLUSTER: trupick-next-cluster
  ECS_SERVICE: trupick-next-service
  TASK_DEF_FILE: ecs-task-def.json         # committed in repo (template)
  LOG_GROUP: /ecs/trupick-next

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (assume IAM role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}   # arn:aws:iam::451117107794:role/gitHub
          role-session-name: gha-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
          output-env-credentials: true

      - name: Verify credentials
        run: aws sts get-caller-identity

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists (optional)
        run: |
          aws ecr describe-repositories --repository-names "$ECR_REPOSITORY" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "$ECR_REPOSITORY"

      - name: Compute image tag
        id: vars
        run: |
          if [ -n "${{ github.event.inputs.image_tag }}" ]; then
            echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=${GITHUB_REF_NAME//\//-}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.vars.outputs.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "IMAGE_URI=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Ensure CloudWatch log group exists (idempotent)
        run: aws logs create-log-group --log-group-name "$LOG_GROUP" || true

      # >>> Inject valid IAM role ARNs into your task definition template <<<
      - name: Inject role ARNs into task def
        run: |
          set -e
          EXEC_ROLE_ARN=$(aws iam get-role --role-name ECSExecRole-ECR --query 'Role.Arn' --output text)
          TASK_ROLE_ARN=$(aws iam get-role --role-name ECSTaskRole-App --query 'Role.Arn' --output text)
          # Replace placeholders in the template file
          sed -i "s#EXEC_ROLE_ARN_HERE#${EXEC_ROLE_ARN}#g" $TASK_DEF_FILE
          sed -i "s#TASK_ROLE_ARN_HERE#${TASK_ROLE_ARN}#g" $TASK_DEF_FILE
          echo "Injected ARNs:"
          grep -E '"executionRoleArn"|"taskRoleArn"' -n $TASK_DEF_FILE || true

      # >>> Swap the image in the (now ARN-injected) task definition <<<
      - name: Render task definition with new image
        run: |
          cat $TASK_DEF_FILE | jq --arg IMAGE_URI "$IMAGE_URI" \
            '.containerDefinitions[0].image = $IMAGE_URI' > task-def-rendered.json
          echo "Rendered task def:"
          cat task-def-rendered.json

      - name: Register new task definition
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://task-def-rendered.json \
            --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
          echo "$TASK_DEF_ARN"

      - name: Update ECS service to new task def
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --task-definition $TASK_DEF_ARN \
            --force-new-deployment

      - name: Wait for service stability
        run: aws ecs wait services-stable --cluster $ECS_CLUSTER --services $ECS_SERVICE
